/*
Autonomous API

Building the next evolution of actionable AI.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AutonomousApi,
  ExtractionApi,
  FeedbackApi,
  TaskApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { InducedAiCustom } from "./client-custom";

export class InducedAi extends InducedAiCustom {
  readonly autonomous: AutonomousApi;
  readonly extraction: ExtractionApi;
  readonly feedback: FeedbackApi;
  readonly task: TaskApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.autonomous = new AutonomousApi(configuration);
    this.extraction = new ExtractionApi(configuration);
    this.feedback = new FeedbackApi(configuration);
    this.task = new TaskApi(configuration);
  }

}
