/* tslint:disable */
/* eslint-disable */
/*
Autonomous API

Building the next evolution of actionable AI.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ExtractionFromUrlRequest } from '../models';
// @ts-ignore
import { ExtractionFromUrlResponse } from '../models';
// @ts-ignore
import { ExtractionGetResultResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ExtractionApi - axios parameter creator
 * @export
 */
export const ExtractionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Extract data from a URL
         * @param {ExtractionFromUrlRequest} extractionFromUrlRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fromUrl: async (extractionFromUrlRequest: ExtractionFromUrlRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'extractionFromUrlRequest' is not null or undefined
            assertParamExists('fromUrl', 'extractionFromUrlRequest', extractionFromUrlRequest)
            const localVarPath = `/extract`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-key", keyParamName: "apiKeyAuth", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: extractionFromUrlRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/extract',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(extractionFromUrlRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get extraction result
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResult: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getResult', 'id', id)
            const localVarPath = `/extract/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-key", keyParamName: "apiKeyAuth", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/extract/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExtractionApi - functional programming interface
 * @export
 */
export const ExtractionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExtractionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Extract data from a URL
         * @param {ExtractionApiFromUrlRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fromUrl(requestParameters: ExtractionApiFromUrlRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExtractionFromUrlResponse>> {
            const extractionFromUrlRequest: ExtractionFromUrlRequest = {
                url: requestParameters.url,
                query: requestParameters.query,
                columns: requestParameters.columns,
                limit: requestParameters.limit,
                format: requestParameters.format
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.fromUrl(extractionFromUrlRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get extraction result
         * @param {ExtractionApiGetResultRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getResult(requestParameters: ExtractionApiGetResultRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExtractionGetResultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getResult(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ExtractionApi - factory interface
 * @export
 */
export const ExtractionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExtractionApiFp(configuration)
    return {
        /**
         * 
         * @summary Extract data from a URL
         * @param {ExtractionApiFromUrlRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fromUrl(requestParameters: ExtractionApiFromUrlRequest, options?: AxiosRequestConfig): AxiosPromise<ExtractionFromUrlResponse> {
            return localVarFp.fromUrl(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get extraction result
         * @param {ExtractionApiGetResultRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getResult(requestParameters: ExtractionApiGetResultRequest, options?: AxiosRequestConfig): AxiosPromise<ExtractionGetResultResponse> {
            return localVarFp.getResult(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for fromUrl operation in ExtractionApi.
 * @export
 * @interface ExtractionApiFromUrlRequest
 */
export type ExtractionApiFromUrlRequest = {
    
} & ExtractionFromUrlRequest

/**
 * Request parameters for getResult operation in ExtractionApi.
 * @export
 * @interface ExtractionApiGetResultRequest
 */
export type ExtractionApiGetResultRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof ExtractionApiGetResult
    */
    readonly id: string
    
}

/**
 * ExtractionApiGenerated - object-oriented interface
 * @export
 * @class ExtractionApiGenerated
 * @extends {BaseAPI}
 */
export class ExtractionApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Extract data from a URL
     * @param {ExtractionApiFromUrlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExtractionApiGenerated
     */
    public fromUrl(requestParameters: ExtractionApiFromUrlRequest, options?: AxiosRequestConfig) {
        return ExtractionApiFp(this.configuration).fromUrl(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get extraction result
     * @param {ExtractionApiGetResultRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExtractionApiGenerated
     */
    public getResult(requestParameters: ExtractionApiGetResultRequest, options?: AxiosRequestConfig) {
        return ExtractionApiFp(this.configuration).getResult(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
