/* tslint:disable */
/* eslint-disable */
/*
Autonomous API

Building the next evolution of actionable AI.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FeedbackSubmissionRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * FeedbackApi - axios parameter creator
 * @export
 */
export const FeedbackApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Provide Feedback for an Autonomous Task
         * @param {string} id 
         * @param {FeedbackSubmissionRequest} feedbackSubmissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submission: async (id: string, feedbackSubmissionRequest: FeedbackSubmissionRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('submission', 'id', id)
            // verify required parameter 'feedbackSubmissionRequest' is not null or undefined
            assertParamExists('submission', 'feedbackSubmissionRequest', feedbackSubmissionRequest)
            const localVarPath = `/autonomous/{id}/feedback`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-key", keyParamName: "apiKeyAuth", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: feedbackSubmissionRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/autonomous/{id}/feedback',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(feedbackSubmissionRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FeedbackApi - functional programming interface
 * @export
 */
export const FeedbackApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FeedbackApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Provide Feedback for an Autonomous Task
         * @param {FeedbackApiSubmissionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submission(requestParameters: FeedbackApiSubmissionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const feedbackSubmissionRequest: FeedbackSubmissionRequest = {
                feedback: requestParameters.feedback
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.submission(requestParameters.id, feedbackSubmissionRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FeedbackApi - factory interface
 * @export
 */
export const FeedbackApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FeedbackApiFp(configuration)
    return {
        /**
         * 
         * @summary Provide Feedback for an Autonomous Task
         * @param {FeedbackApiSubmissionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submission(requestParameters: FeedbackApiSubmissionRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.submission(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for submission operation in FeedbackApi.
 * @export
 * @interface FeedbackApiSubmissionRequest
 */
export type FeedbackApiSubmissionRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof FeedbackApiSubmission
    */
    readonly id: string
    
} & FeedbackSubmissionRequest

/**
 * FeedbackApiGenerated - object-oriented interface
 * @export
 * @class FeedbackApiGenerated
 * @extends {BaseAPI}
 */
export class FeedbackApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Provide Feedback for an Autonomous Task
     * @param {FeedbackApiSubmissionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbackApiGenerated
     */
    public submission(requestParameters: FeedbackApiSubmissionRequest, options?: AxiosRequestConfig) {
        return FeedbackApiFp(this.configuration).submission(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
