/*
Autonomous API

Building the next evolution of actionable AI.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExtractionFromUrlResponseData
 */
export interface ExtractionFromUrlResponseData {
    /**
     * 
     * @type {string}
     * @memberof ExtractionFromUrlResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractionFromUrlResponseData
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtractionFromUrlResponseData
     */
    'objective'?: string;
}

