/*
Autonomous API

Building the next evolution of actionable AI.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TaskExecuteResponseData
 */
export interface TaskExecuteResponseData {
    /**
     * 
     * @type {string}
     * @memberof TaskExecuteResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskExecuteResponseData
     */
    'streamingUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskExecuteResponseData
     */
    'watchUrl'?: string;
}

