/*
Autonomous API

Building the next evolution of actionable AI.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TaskExecuteResponseData } from './task-execute-response-data';

/**
 * 
 * @export
 * @interface TaskExecuteResponse
 */
export interface TaskExecuteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TaskExecuteResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {TaskExecuteResponseData}
     * @memberof TaskExecuteResponse
     */
    'data'?: TaskExecuteResponseData;
    /**
     * 
     * @type {string}
     * @memberof TaskExecuteResponse
     */
    'requestId'?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskExecuteResponse
     */
    'timeTaken'?: number;
}

